# Generated by Django 4.2.6 on 2023-11-04 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('published_year', models.DateField()),
                ('publisher', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('f', 'Fiction'), ('nf', 'Non-Fiction'), ('t', 'Thriller'), ('sh', 'Self-Help'), ('h', 'History'), ('s', 'Science')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_day', models.DateField(auto_now_add=True)),
                ('return_day', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed', models.IntegerField()),
                ('returned', models.IntegerField(blank=True, null=True)),
                ('book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.book')),
                ('borrow_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.borrow')),
            ],
            options={
                'ordering': ['borrow_id', 'book_id'],
            },
        ),
        migrations.AddField(
            model_name='borrow',
            name='member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.member'),
        ),
        migrations.AddConstraint(
            model_name='detail',
            constraint=models.UniqueConstraint(fields=('borrow_id', 'book_id'), name='unique_borrow_id_book_id_combination'),
        ),
    ]
