# Generated by Django 4.2.6 on 2023-10-19 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TacGia',
            fields=[
                ('ma_tac_gia', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ten_tac_gia', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['ma_tac_gia'],
            },
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('ma_the_loai', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ten_the_loai', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['ma_the_loai'],
            },
        ),
        migrations.CreateModel(
            name='TheThanhVien',
            fields=[
                ('ma_the', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cccd', models.CharField(max_length=12)),
                ('ho_va_ten', models.CharField(max_length=50)),
                ('dia_chi', models.CharField(max_length=200)),
                ('sdt', models.CharField(max_length=10)),
                ('ngay_cap', models.DateField()),
            ],
            options={
                'ordering': ['ma_the'],
            },
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('ma_sach', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ten_sach', models.CharField(max_length=50)),
                ('nam_xuat_ban', models.DateField()),
                ('nha_xuat_ban', models.CharField(max_length=50)),
                ('gia', models.IntegerField()),
                ('so_luong', models.IntegerField()),
                ('tac_gia', models.ManyToManyField(to='manager.tacgia')),
                ('the_loai', models.ManyToManyField(to='manager.theloai')),
            ],
            options={
                'ordering': ['ma_sach'],
            },
        ),
        migrations.CreateModel(
            name='BieuMauMuonTra',
            fields=[
                ('ma_bieu_mau', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ngay_muon', models.DateField()),
                ('ngay_hen_tra', models.DateField()),
                ('ngay_tra', models.DateField()),
                ('ma_the', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.thethanhvien')),
            ],
            options={
                'ordering': ['ma_bieu_mau'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietBieuMauMuonTra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('so_sach_nhan_lai', models.IntegerField()),
                ('ma_bieu_mau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.bieumaumuontra')),
                ('ma_the', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.thethanhvien')),
            ],
            options={
                'ordering': ['ma_bieu_mau', 'ma_the'],
                'unique_together': {('ma_bieu_mau', 'ma_the')},
            },
        ),
    ]
