# Generated by Django 4.2.6 on 2023-11-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Thriller', 'Thriller'), ('Self-Help', 'Self-Help'), ('History', 'History'), ('Science', 'Science')], max_length=50),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
