# Generated by Django 4.2.6 on 2023-10-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='return_day',
            field=models.DateField(null=True),
        ),
    ]
