# Generated by Django 4.2.5 on 2023-10-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_chitietbieumaumuontra_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietbieumaumuontra',
            name='ma_bieu_mau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.bieumaumuontra'),
        ),
        migrations.AlterField(
            model_name='chitietbieumaumuontra',
            name='ma_the',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.thethanhvien'),
        ),
    ]
