# Generated by Django 4.2.6 on 2023-11-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_detail_returned'),
        ('manager', '0003_alter_detail_returned_and_more'),
    ]

    operations = [
    ]
