# Generated by Django 4.2.6 on 2023-11-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_merge_20231111_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='Default description', max_length=500),
            preserve_default=False,
        ),
    ]
