# Generated by Django 4.2.6 on 2023-11-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_detail_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='returned',
            field=models.IntegerField(null=True),
        ),
    ]
